stages:
  data_ingestion_and_preprocessing:
    cmd: python -m src.data.data_ingestion_and_preprocessing
    deps:
      - src/data/data_ingestion_and_preprocessing.py
    params:
      - data_ingestion.data_path
      - data_ingestion.test_size
    outs:
      - data/raw
      - data/processed

  model_training:
    cmd: python -m src.model.model_building
    deps:
      - data/processed/preprocessed_train.csv
      - src/model/model_building.py
    params:
      - model_building.ngram_range
      - model_building.max_features
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    outs:
      - saved_model/tfidf_vectorizer.pkl
      - saved_model/lgbm_model.pkl

  model_evaluation:
    cmd: python -m src.model.model_evaluation
    deps:
      - data/processed/preprocessed_test.csv
      - saved_model/tfidf_vectorizer.pkl
      - saved_model/lgbm_model.pkl
      - src/model/model_evaluation.py
    params:
      - model_evaluation.test_data_path
    outs:
      - experiment_model_info.json
  
  model_registration:
    cmd: python -m src.model.model_register
    deps:
      - experiment_model_info.json
      - src/model/model_register.py
    